---
version: "3.7"

services:

  # pre installs all of the python dependencies, including for integration tests
  _galaxy_base:
    build:
      args:
        DJANGO_ANSIBLE_BASE_BRANCH: "2025.3.7"
        
    environment:
      DJANGO_ANSIBLE_BASE_BRANCH: "2025.3.7"

  pulp:
    environment:
      PULP_WORKERS: "1"
      DJANGO_ANSIBLE_BASE_BRANCH: "2025.3.7"

volumes:
  pulp_certs:
