[allowlist]
  description = "Our test install exports a test only MINIO ACCESS KEY"
  paths = [
    "openshift/clowder/clowd-app.yaml",
    "dev/Dockerfile.base",
    "dev/standalone-ldap/galaxy_ng.env",
    "galaxy_ng/tests",
    "dev/compose/signing/keys/signing-secret.key",
    "dev/compose/signing/keys/signing-secret.key.password.txt",
    "/dev/compose/"
  ]
