# Add any custom services for your profile here.

version: "3.7"

services:
  # ui:
  #   environment:
  #     - "API_PROXY_HOST=pulp"
  #     - "API_PROXY_PORT={API_PORT}"
  #     - "DEPLOYMENT_MODE=standalone"
  #     - "API_BASE_PATH=/api/galaxy/"
  #     - "UI_EXTERNAL_LOGIN_URI={API_PROTOCOL}://{API_HOST}:{API_PORT}/login"

  keycloak:
    #image: quay.io/keycloak/keycloak:legacy
    image: quay.io/keycloak/keycloak:latest
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=kc-postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=keycloak
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KC_HTTP_RELATIVE_PATH=/auth
    ports:
      - 8080:8080
    depends_on:
      - kc-postgres
      - ldap
    command: ['start-dev']

  kc-postgres:
    image: "postgres:12"
    volumes:
      - kc_pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak

  ldap:
    image: "rroemhild/test-openldap"
    ports:
      - "10389:10389"
      - "10636:10636"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  kc_pg_data:
    name: "{COMPOSE_PROJECT_NAME}kc_pg_data"
