---
version: "3.7"

services:
  _base:
    build:
      context: "${COMPOSE_CONTEXT}"
      dockerfile: "dev/Dockerfile.base"
      args:
        LOCK_REQUIREMENTS: "${LOCK_REQUIREMENTS}"
        COMPOSE_PROFILE: "${COMPOSE_PROFILE}"
        DEV_SOURCE_PATH: "${DEV_SOURCE_PATH}"
        DEV_IMAGE_SUFFIX: "${DEV_IMAGE_SUFFIX:-}"
        DEV_VOLUME_SUFFIX: "${DEV_VOLUME_SUFFIX:-${DEV_IMAGE_SUFFIX:-}}"
    image: "localhost/galaxy_ng/galaxy_ng:base${DEV_IMAGE_SUFFIX:-}"
    environment:
      - "WITH_DEV_INSTALL=${WITH_DEV_INSTALL}"
      - "LOCK_REQUIREMENTS=${LOCK_REQUIREMENTS}"
      - "DEV_SOURCE_PATH=${DEV_SOURCE_PATH}"
      - "COMPOSE_PROFILE=${COMPOSE_PROFILE}"
      - "ENABLE_SIGNING=${ENABLE_SIGNING}"
    entrypoint: "/bin/true"
    tmpfs:
      - "/var/lib/pulp/artifact"
      - "/var/lib/pulp/scripts"
      - "/var/lib/pulp/tmp"
      - "/tmp/ansible"

  api:
    build:
      context: "${COMPOSE_CONTEXT}"
      dockerfile: "dev/${COMPOSE_PROFILE}/Dockerfile"
      args:
        DEV_IMAGE_SUFFIX: "${DEV_IMAGE_SUFFIX:-}"
        DEV_VOLUME_SUFFIX: "${DEV_VOLUME_SUFFIX:-${DEV_IMAGE_SUFFIX:-}}"
    image: "localhost/galaxy_ng/galaxy_ng:${COMPOSE_PROFILE}${DEV_IMAGE_SUFFIX:-}"
    command: ['run', 'api-reload']
    ports:
      - "5001:8000"
    environment:
      - "WITH_DEV_INSTALL=${WITH_DEV_INSTALL}"
      - "LOCK_REQUIREMENTS=${LOCK_REQUIREMENTS}"
      - "DEV_SOURCE_PATH=${DEV_SOURCE_PATH}"
      - "COMPOSE_PROFILE=${COMPOSE_PROFILE}"
      - "ENABLE_SIGNING=${ENABLE_SIGNING}"
    env_file:
      - './common/galaxy_ng.env'
    volumes:
      - "./common/settings.py:/etc/pulp/settings.py:z"
      - "./common/dynaconf_hooks.py:/etc/pulp/dynaconf_hooks.py:z"
      - "./common/collection_sign.sh:/var/lib/pulp/scripts/collection_sign.sh:z"
      - "./common/container_sign.sh:/var/lib/pulp/scripts/container_sign.sh:z"
      - "${COMPOSE_CONTEXT}/..:/src:z"
      - "pulp:/var/lib/pulp"
    tmpfs:
      - "/tmp/ansible:uid=1000,gid=1000"
    depends_on:
      - _base
      - postgres
      - redis

  worker:
    image: "localhost/galaxy_ng/galaxy_ng:${COMPOSE_PROFILE}${DEV_IMAGE_SUFFIX:-}"
    command: ['run', 'worker-reload']
    environment:
      - "WITH_DEV_INSTALL=${WITH_DEV_INSTALL}"
      - "LOCK_REQUIREMENTS=${LOCK_REQUIREMENTS}"
      - "DEV_SOURCE_PATH=${DEV_SOURCE_PATH}"
      - "COMPOSE_PROFILE=${COMPOSE_PROFILE}"
      - "ENABLE_SIGNING=${ENABLE_SIGNING}"
    env_file:
      - './common/galaxy_ng.env'
    volumes:
      - "./common/settings.py:/etc/pulp/settings.py:z"
      - "./common/collection_sign.sh:/var/lib/pulp/scripts/collection_sign.sh:z"
      - "./common/container_sign.sh:/var/lib/pulp/scripts/container_sign.sh:z"
      - "${COMPOSE_CONTEXT}/..:/src:z"
      - "pulp:/var/lib/pulp"
    tmpfs:
      - "/tmp/ansible:uid=1000,gid=1000"
    depends_on:
      - _base
      - postgres
      - redis
    deploy:
      replicas: 2

  content-app:
    image: "localhost/galaxy_ng/galaxy_ng:${COMPOSE_PROFILE}${DEV_IMAGE_SUFFIX:-}"
    command: ['run', 'content-app']
    ports:
      - "24816:24816"
    environment:
      - "WITH_DEV_INSTALL=${WITH_DEV_INSTALL}"
      - "LOCK_REQUIREMENTS=${LOCK_REQUIREMENTS}"
      - "DEV_SOURCE_PATH=${DEV_SOURCE_PATH}"
      - "COMPOSE_PROFILE=${COMPOSE_PROFILE}"
      - "ENABLE_SIGNING=${ENABLE_SIGNING}"
    env_file:
      - './common/galaxy_ng.env'
    volumes:
      - "./common/settings.py:/etc/pulp/settings.py:z"
      - "./common/collection_sign.sh:/var/lib/pulp/scripts/collection_sign.sh:z"
      - "./common/container_sign.sh:/var/lib/pulp/scripts/container_sign.sh:z"
      - "${COMPOSE_CONTEXT}/..:/src:z"
      - "pulp:/var/lib/pulp"
    tmpfs:
      - "/tmp/ansible:uid=1000,gid=1000"
    depends_on:
      - _base
      - postgres
      - redis

  postgres:
    image: "postgres:12"
    ports:
      - "5432:5432"
    env_file:
      - './common/postgres.env'
    volumes:
      - "pg_data:/var/lib/postgresql/data"

  redis:
    image: "redis:5"
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/data"


  swagger-ui:
   image: swaggerapi/swagger-ui
   ports:
      - "8003:8080"
  #  volumes:
  #     - ./doc:/usr/share/nginx/html/doc
   environment:
      API_URL: http://0.0.0.0:5001/api/automation-hub/v3/openapi.json


volumes:
  pulp:
    name: pulp${DEV_VOLUME_SUFFIX:-}
  pg_data:
    name: pg_data${DEV_VOLUME_SUFFIX:-}
  redis_data:
    name: redis_data${DEV_VOLUME_SUFFIX:-}
