---
version: "3.7"

services:
  api:
    env_file:
      - './automation-hub/standalone/galaxy_ng.env'
  resource-manager:
    env_file:
      - './automation-hub/standalone/galaxy_ng.env'
  worker:
    env_file:
      - './automation-hub/standalone/galaxy_ng.env'
  content-app:
    env_file:
      - './automation-hub/standalone/galaxy_ng.env'
