---
version: "3.7"

services:
  _base:
    build:
      context: "${COMPOSE_CONTEXT}"
      dockerfile: "dev/Dockerfile.base"
    image: "localhost/galaxy_ng/galaxy_ng:base"
    entrypoint: "/bin/true"
    tmpfs:
      - "/var/lib/pulp/artifact"
      - "/var/lib/pulp/tmp"
      - "/tmp/ansible"

  api:
    build:
      context: "${COMPOSE_CONTEXT}"
      dockerfile: "dev/${COMPOSE_PROFILE}/Dockerfile"
    image: "localhost/galaxy_ng/galaxy_ng:${COMPOSE_PROFILE}"
    command: ['run', 'api-reload']
    ports:
      - "5001:8000"
    environment:
      - "WITH_DEV_INSTALL=1"
      - "DEV_SOURCE_PATH=${DEV_SOURCE_PATH}"
    env_file:
      - './common/galaxy_ng.env'
    volumes:
      - "./common/settings.py:/etc/pulp/settings.py:z"
      - "${COMPOSE_CONTEXT}/..:/src:z"
      - "pulp:/var/lib/pulp"
    tmpfs:
      - "/tmp/ansible:uid=1000,gid=1000"
    depends_on:
      - _base
      - postgres
      - redis

  resource-manager:
    image: "localhost/galaxy_ng/galaxy_ng:${COMPOSE_PROFILE}"
    command: ['run', 'resource-manager']
    environment:
      - "WITH_DEV_INSTALL=1"
      - "DEV_SOURCE_PATH=${DEV_SOURCE_PATH}"
    env_file:
      - './common/galaxy_ng.env'
    volumes:
      - "./common/settings.py:/etc/pulp/settings.py:z"
      - "${COMPOSE_CONTEXT}/..:/src:z"
      - "pulp:/var/lib/pulp"
    tmpfs:
      - "/tmp/ansible:uid=1000,gid=1000"
    depends_on:
      - _base
      - postgres
      - redis

  worker:
    image: "localhost/galaxy_ng/galaxy_ng:${COMPOSE_PROFILE}"
    command: ['run', 'worker']
    environment:
      - "WITH_DEV_INSTALL=1"
      - "DEV_SOURCE_PATH=${DEV_SOURCE_PATH}"
    env_file:
      - './common/galaxy_ng.env'
    volumes:
      - "./common/settings.py:/etc/pulp/settings.py:z"
      - "${COMPOSE_CONTEXT}/..:/src:z"
      - "pulp:/var/lib/pulp"
    tmpfs:
      - "/tmp/ansible:uid=1000,gid=1000"
    depends_on:
      - _base
      - postgres
      - redis

  content-app:
    image: "localhost/galaxy_ng/galaxy_ng:${COMPOSE_PROFILE}"
    command: ['run', 'content-app']
    ports:
      - "24816:24816"
    environment:
      - "WITH_DEV_INSTALL=1"
      - "DEV_SOURCE_PATH=${DEV_SOURCE_PATH}"
    env_file:
      - './common/galaxy_ng.env'
    volumes:
      - "./common/settings.py:/etc/pulp/settings.py:z"
      - "${COMPOSE_CONTEXT}/..:/src:z"
      - "pulp:/var/lib/pulp"
    tmpfs:
      - "/tmp/ansible:uid=1000,gid=1000"
    depends_on:
      - _base
      - postgres
      - redis

  postgres:
    image: "postgres:11"
    ports:
      - "5432:5432"
    env_file:
      - './common/postgres.env'
    volumes:
      - "pg_data:/var/lib/postgresql/data"

  redis:
    image: "redis:5"
    volumes:
      - "redis_data:/data"


volumes:
  pulp: {}
  pg_data: {}
  redis_data: {}
