---
version: "3.7"

services:
  api:
    env_file:
      - './standalone/galaxy_ng.env'
  worker:
    env_file:
      - './standalone/galaxy_ng.env'
  content-app:
    env_file:
      - './standalone/galaxy_ng.env'
