---
name: Standalone IQE RBAC tests
on: 
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Update apt
        run: sudo apt -y update

      - name: Install LDAP requirements
        run: sudo apt-get install -y libsasl2-dev python3 libldap2-dev libssl-dev build-essential

      - name: Install python requirements required to run integration tests
        run: pip install requests pyyaml

      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.17.3'

      - name: create the .compose.env file
        run: rm -f .compose.env; cp .compose.env.example .compose.env

      - name: workaround github worker permissions issues
        run: sed -i.bak 's/PIP_EDITABLE_INSTALL=1/PIP_EDITABLE_INSTALL=0/' .compose.env

      - name: workaround github worker permissions issues
        run: sed -i.bak 's/WITH_DEV_INSTALL=1/WITH_DEV_INSTALL=0/' .compose.env

      - name: build stack
        run: make docker/all

      - name: start the compose stack
        run: ./compose up -d

      - name: give stack some time to spin up
        run: COMPOSE_INTERACTIVE_NO_CLI=1 python dev/common/poll.py

      - name: set keyring on staging repo for signature upload
        run: ./compose exec -T api ./entrypoint.sh manage set-repo-keyring --repository staging --keyring /etc/pulp/certs/galaxy.kbx -y

      #- name: install python 3.10
      #  run: sudo apt install software-properties-common -y; sudo add-apt-repository --yes ppa:deadsnakes/ppa; sudo apt install python3.10

      - name: run the integration tests
        run: ./dev/standalone-iqe-tests/RUN_RBAC_INTEGRATION.sh
