---
name: Local Standalone Sync Against Local Insights
on: 
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Note: COMPOSE_INTERACTIVE_NO_CLI=1 is required for oci-env to work correctly when there's no interactive terminal
      - name: Set environment variables
        run: |
          echo "OCI_ENV_PATH=${HOME}/work/galaxy_ng/oci_env" >> $GITHUB_ENV
          echo "COMPOSE_INTERACTIVE_NO_CLI=1" >> $GITHUB_ENV

      - name: Update apt
        run: sudo apt -y update

      - name: Install LDAP requirements
        run: sudo apt-get install -y libsasl2-dev python3 libldap2-dev libssl-dev build-essential

      - name: Install python requirements required to run integration tests
        run: pip install requests pyyaml

      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.17.3'

      - name: setup oci-env
        run: |
          git clone https://github.com/pulp/oci_env.git $OCI_ENV_PATH
          pip install -e $OCI_ENV_PATH/client/
          mkdir $OCI_ENV_PATH/db_backup/
          cp dev/data/insights-fixture.tar.gz $OCI_ENV_PATH/db_backup/insights-fixture.tar.gz

      - name: launch test instances
        run: |
          oci-env -e dev/oci_env_configs/sync-test.compose.env compose build
          oci-env -e dev/oci_env_configs/sync-test.compose.env compose up -d
          oci-env -e dev/oci_env_configs/standalone.compose.env compose up -d

      - name: wait for test instances to come online
        run: |
          oci-env -e dev/oci_env_configs/standalone.compose.env poll --wait 10 --attempts 30
          oci-env -e dev/oci_env_configs/sync-test.compose.env poll

      - name: give the stack extra time to start
        run: sleep 30

      - name: finish insights instance setup
        run: |
          oci-env -e dev/oci_env_configs/sync-test.compose.env db restore -f insights-fixture --migrate
          oci-env -e dev/oci_env_configs/sync-test.compose.env pulpcore-manager migrate
          oci-env -e dev/oci_env_configs/sync-test.compose.env poll

      - name: give the stack extra time to re-start
        run: sleep 30

      - name: run the integration tests
        run: ./dev/standalone-certified-sync/RUN_INTEGRATION.sh
