---
name: TDD
on: 
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:

  validation:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: make the checkout in a sane way.
        run: |
            curl -o /tmp/pr.diff https://patch-diff.githubusercontent.com/raw/ansible/galaxy_ng/pull/${GITHUB_PR_NUMBER}.diff
            git clone https://github.com/ansible/galaxy_ng
            cd galaxy_ng
            git checkout -b "${{ github.head_ref }}"
            git apply /tmp/pr.diff
        env:
          GITHUB_PR_NUMBER: ${{github.event.number}}

      - name: Ensure changes were made to tests
        env:
          PY_COLORS: '1'
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_BRANCH: ${{ github.head_ref }}
          GITHUB_USER: ${{ github.event.pull_request.user.login }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: cd galaxy_ng; python dev/common/tdd.py
